# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: JetThoughts
url: https://jetthoughts.com
description: Hire us to build you a world-class iOS, Android, or web app. Find Ruby on Rails, Vue.js and React Native developers.
title: Ruby on Rails, React, Mobile & Web Development
keywords: dev shop, consulting, ruby, rails, node, ios, android, java, javascript, software development companies in chicago, software development companies in los angeles, software development companies in new york, mobile application development, android developer, mobile app development, app developer, top mobile app development companies, mobile app development company, ios developer

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bin
  - gulpfile
  - package
  - yarn
  - src

assets:
  compress:
    css: true
    js: true
  sources:
    - _assets/css/
    - _assets/fonts
    - _assets/javascripts/
    - _assets/images/
  autoprefixer:
      browsers:
        - "last 2 versions"
        - "IE > 10"
